language: java
dist: trusty
sudo: required

jdk:
  - oraclejdk8
after_success:
  - bash <(curl -s https://codecov.io/bash)


services:
  - mysql

install: true

before_script:
  - mysql -e 'CREATE DATABASE academy;'

script:
  - mvn -q compile flyway:clean flyway:migrate install --settings settings.xml


notifications:
  email:
  - herve.tchepannou@gmail.com

#deploy:
#  provider: heroku
#  api_key: $HEROKU_API_KEY
#  app: io-tchepannou-academy-service
#  on: master
