language: java
dist: trusty
sudo: required

jdk: oraclejdk8


services:
  - mysql

install: true

before_script:
  - mysql -e 'CREATE DATABASE academy;'

script:
  - mvn -q compile flyway:clean flyway:migrate install --settings settings.xml

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 950f795f-761b-42cb-8c12-39c555b48382

notifications:
  email:
  - herve.tchepannou@gmail.com

#deploy:
#  provider: heroku
#  api_key: $HEROKU_API_KEY
#  app: io-tchepannou-academy-service
#  on: master
