spring:
  datasource:
    url: jdbc:mysql://ffn96u87j5ogvehy.cbetxkdyhwsb.us-east-1.rds.amazonaws.com/fpngoug8qewcl5e7?reconnect=true
    username: plivwbkhx8r6ftmh
    password: lmoqznvfp686jmb2

flyway:
  user: ${spring.datasource.username}
  password: ${spring.datasource.password}
  url: ${spring.datasource.url}

swagger:
  protocol: https
