spring:
  datasource:
    url: jdbc:mysql://k.cwj11t2vidmo.us-east-1.rds.amazonaws.com/academy_user?reconnect=true
    username: ${database.user}
    password: ${database.password}

flyway:
  user: ${spring.datasource.username}
  password: ${spring.datasource.password}
  url: ${spring.datasource.url}

swagger:
  protocol: https
