DELETE FROM T_QUIZ_CHOICE;
DELETE FROM T_QUIZ;
DELETE FROM T_COURSE_ATTENDANCE;
DELETE FROM T_SEGMENT_ATTENDANCE;
DELETE FROM T_VIDEO;
DELETE FROM T_SEGMENT;
DELETE FROM T_LESSON;
DELETE FROM T_COURSE;
